### PR TITLE
Add GetSingleItemData to get raw data with individual selectors

### PR DESCRIPTION
**Pull request by gnadelwartz**
I was looking for a simple solution to request item data from ebay. Most solutions are complex to use or outdated. So I was happy to find your API-Wrapper providing exactly what I've looked for.

As wanted to access [all Data](https://developer.ebay.com/devzone/shopping/docs/callref/getsingleitem.html) but to be more flexible I  added the function 'GetSingleItemData()'.
In Addtion I made the API selector parameter an optional argument. ''GetSingleItem()' works as before.

I'm now able to request specific data for Items and do better error processing: 

```php
    $ebay_api = new ebay_api();
    $data = $ebay_api->GetSingleItemData("1xxxxxxxxxx5", "77", false, ""); //only minimum selectors is faster

    if(isset($data->Ack) && $data->Ack == "Success") {
        print("Titel: ".$data->Item->Title.PHP_EOL);
    } else {
        if (isset($data->Errors->ErrorCode)) {
            print("{$data->Timestamp} Error {$data->Errors->ErrorCode}: {$data->Errors->LongMessage}".PHP_EOL);
        } else {
            print("Unknown Error: Dumpimg Data ...".PHP_EOL.$data.PHP_EOL);
        }
    }

```

May be you find it usefull ...

### CODE REVIEW

**Comment by gnadelwartz** [comment]
The regex to get the itm-ID is not optimal, I changed GetItemId to use retrun the match part in '(\d{12})' only and provide an better but alternative regex.

```php
  // Gnadelwartz: IMHO itemid is always prefixed by  '/' and postfixed with  '/' or '?' or newline ('$')
  // uncomment to activate
  // $regex = '/\/(\d{12})[\/?]/m';

```

**Comment by gnadelwartz** [comment]
replace 'case xxx in ...' with associative array: faster, less code

**Comment by CainDev** [comment]
I am so sorry I haven't responded in such a long time. I have been so busy with other projects I have been working on I have completely forgotten all about this lil wrapper. I really appreciate your contributions and will merge them now. Thank you so much :)

**Comment by CainDev** [comment]
Also as a budding developer I appreciate the explanations of what can be improved on, I genuinely appreciate it. I love to learn.

Cheers once again 👍

**Pull request merged**
